#!/usr/bin/env python

libname = "godot-crypto"

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/", "libcsl/"])
sources = Glob("src/*.cpp")

env.Append(LIBS=["csl"])
env.Append(LIBPATH=['.'])

if env["platform"] == "macos":
    platlibname = "{}.{}.{}".format(libname, env["platform"], env["target"])
    library = env.SharedLibrary(
        "bin/{}.framework/{}".format(platlibname, platlibname),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/{}{}{}".format(libname, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
