site_name: godot-cardano
site_description: Godot Cardano Addon
site_url: https://github.com/mlabs-haskell/godot-cardano

repo_url: https://github.com/mlabs-haskell/godot-cardano
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - scheme: default
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - tables
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - README: index.md
  - GDScript Reference:
#REFERENCE

extra:
  homepage: https://mlabs-haskell.github.io/godot-cardano/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mlabs-haskell/godot-cardano
      name: godot-cardano on Github
  generator: false # hide the line "Made with Material for MkDocs"

extra_css:
  - extra.css

copyright: Copyright &copy; MLabs Ltd
