name: Build
on: push

jobs:
  build:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - uses: cachix/cachix-action@v13
        with:
          name: mlabs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Build GDExtension for Windows
        run: nix build .#libcsl_godot-win

      - uses: actions/upload-artifact@v4
        with:
          path: result/bin/csl_godot.dll
          name: libcsl_godot-win

      - name: Build Demo app for Windows
        run: nix build .#csl_demo-win

      - uses: actions/upload-artifact@v4
        with:
          path: result/bin/
          name: csl_demo-win
