name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: "ubuntu-22.04"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - uses: cachix/cachix-action@v13
        with:
          name: mlabs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Build/Download
        run: nix build .#libcsl_godot .#libcsl_godot-win .#csl_demo .#csl_demo-win

      - name: Prepare release
        run: |
          mkdir release release-prep
          cp result/lib/libcsl_godot.so release/
          cp result-1/bin/csl_godot.dll release/
          cp -r result-2/bin release-prep/csl_demo
          cp -r result-3/bin release-prep/csl_demo-win

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/csl_demo-linux.zip release-prep/csl_demo

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/csl_demo-win.zip release-prep/csl_demo-win

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: release-${{ github.sha }}

      - uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.sha }}
          commit: ${{ github.sha }}
          artifacts: "release/*"
