name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: "ubuntu-22.04"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - uses: cachix/cachix-action@v13
        with:
          name: mlabs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Download / Build
        run: nix build .#godot-cardano .#demo .#demo-windows

      - name: Pack Release
        run: |
          mkdir release release-prep
          cp -r result/addons release-prep
          cp -r result-1/bin release-prep/godot-cardano-demo-linux
          cp -r result-2/bin release-prep/godot-cardano-demo-windows
          cd release-prep
          zip -qq -r ../release/godot-cardano-addon.zip addons
          zip -qq -r ../release/godot-cardano-demo-linux.zip godot-cardano-demo-linux
          zip -qq -r ../release/godot-cardano-demo-windows.zip godot-cardano-demo-windows

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: release-${{ github.sha }}

      - uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.sha }}
          commit: ${{ github.sha }}
          artifacts: "release/*"
