name: preview-test
on: push

jobs:
  test:
    runs-on: "ubuntu-22.04"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - uses: cachix/cachix-action@v13
        with:
          name: mlabs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Download / Build
        run: nix build .#preview-integration-test

      - name: Run Integration Test on Public Preview Testnet
        run: |
          [ -z "${{ secrets.TESTNET_SEED_PHRASE }}" ] && echo "Secret is available."
          nix run -L .#preview-integration-test
        env:
          TESTNET_SEED_PHRASE: '${{ secrets.TESTNET_SEED_PHRASE }}'
